### ISSUE TITLE
Dashboards should be provisioning compatible

### ISSUE THREAD

**Issue by aditya-konarde** [redhat-developer/che-monitoring#5]
The Che dashboards are currently exported in a way that they fail loading a grafana which uses provisioning. 

To fix this, we need the dashboards to be exported by selecting the `Export for sharing externally` in the `Export` tab of the share dashboard window.

**Comment by aditya-konarde** [comment]
I finished doing this for one of the dashboards. 

@skabashnyuk can you take the JVM one?

**Comment by skabashnyuk** [comment]
CC @ibuziuk can you take a look?

**Comment by ibuziuk** [comment]
I think this one can be closed due to https://github.com/eclipse/che/issues/14652
